VAR dialogoTV = 0
VAR teste = true
VAR exameRemedio = 0
VAR exameGavetaFechada = 0
VAR exameFogao = 0
VAR exameCama = 0
VAR exameArmario = 0
VAR examePresunto = 0
VAR exameTesoura = 0
VAR exameRevista = 0

=== function resetDialogueVariables() ===
~ dialogoTV = 0
~ teste = true
~ exameRemedio = 0
~ exameGavetaFechada = 0
~ exameFogao = 0
~ exameCama = 0
~ exameArmario = 0
~ examePresunto = 0
~ exameTesoura = 0
~ exameRevista = 0